version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
platform: x64
clone_folder: C:\projects\restbed
#init:
#- cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: >-
    echo "Building OpenSSL Dependency..."
    
    echo %path%
    
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
    
    echo %path%

    cd c:\projects\restbed\dependency\openssl

    perl Configure VC-WIN64A

    ms\do_win64a

    nmake -f ms\ntdll.mak

    set PATH=C:\projects\restbed\dependency\openssl\out32dll;%PATH%
    
    echo %path%

    echo "Building Restbed..."

    mkdir c:\projects\restbed\build

    cd c:\projects\restbed\build

    cmake -G "Visual Studio 14 2015" -DBUILD_SSL=YES -DBUILD_EXAMPLES=NO -DBUILD_TESTS=YES ..

    cmake --build . --target ALL_BUILD --config Release
test_script:
- cmd: >-
    cd c:\projects\restbed\build

    ctest
deploy: off
